### PR TITLE
Update testname mapping for renamed tests due to new apps.openshift.io dependency

### PR DESCRIPTION
**Pull request by ingvagabund**
Update after https://github.com/openshift/origin/pull/28951.

### CODE REVIEW

**Comment by stbenjam** [comment]
You'll need to run `make mapping` to see the updates

(Btw tests will automatically run for you if you join the openshift-eng org)

**Comment by ingvagabund** [comment]
I can see only 2 members in that org: https://github.com/orgs/openshift-eng/people. Are there more that I can't see?

**Pull request merged**
